### ISSUE TITLE
Gradle files are incomplete

### ISSUE THREAD

**Issue by Leviathan143** [TeamWizardry/LibrarianLib#1]
It is conventional to upload the gradle folder(gradle not .gradle), both gradle build scripts and the build.gradle in mod git repos. This allows someone to fork, clone and then run gradlew setupDecompWorkspace straight away, rather than having to download the appropriate MDK to get the missing files first.

**Comment by LordSaad44** [comment]
You don't download the MDK though. You pull and it should directly download all the required libs/packages including forge in either setupdecompworkspace or genintellijruns/geneclipseruns.

I've never had to download the forge MDK myself to work with my projects

**Comment by Leviathan143** [comment]
@LordSaad44 
That requires the gradle wrapper, which is not present in this repo.
