### ISSUE TITLE
setRenderLayerNormal in particleBuilder enables blending regardless

### ISSUE THREAD

**Issue by LordSaad44** [TeamWizardry/LibrarianLib#11]
It's supposed to disable blending but it uses it anyways.

**Comment by thecodewarrior** [comment]
It keeps blending, it just isn't additive.

**Comment by yrsegal** [comment]
but it is additive, codewarrior

**Comment by thecodewarrior** [comment]
Oh... _thought he fixed all these things long ago_.

**Comment by thecodewarrior** [comment]
I can't seem to reproduce this in dev, is it still an issue?

**Comment by yrsegal** [comment]
yes

**Comment by LordSaad44** [comment]
Been fixed for a while now.
