### ISSUE TITLE
SpongeForge server PLEASE FIX THIS HURRY UP

### ISSUE THREAD

**Issue by krisjenner** [TeamWizardry/LibrarianLib#111]
https://github.com/TeamWizardry/LibrarianLib/issues/77

STILL A PROBLEM ON librarianlib-1.12.2-4.19.1-release.jar PLEASE FIX THIS MY CHILDREN ARE DYING

**Comment by Bluexin** [comment]
THIS IS KNOWN YOU DON'T NEED TO USE CAPS AND SPAM ISSUES NOR BE RUDE
