### ISSUE TITLE
liblib causes other mods' particles  to render as white

### ISSUE THREAD

**Issue by majijn** [TeamWizardry/LibrarianLib#115]
tested with roots + dependencies and liblib + its dependencies
removing liblib fixes it.

**Comment by thecodewarrior** [comment]
Does it cause all mods' particles to render white, or just roots'?

**Comment by majijn** [comment]
root's and embers, at least.

**Comment by Bluexin** [comment]
Did it start popping up with specific versions of any of these ?
I'll ask the devs whether they changed anything to their particle systems recently.

Edit: which roots & embers are we talking about here? there's so many versions/forks x) the ones from the Mystical team ?

**Comment by majijn** [comment]
im not sure, i only noticed it after i added hooked to the pack where i was playing aroung with roots chiefly.

roots 3, and embers rekindled.

**Comment by Bluexin** [comment]
Alright, then I know how to contact the authors, thanks.

**Comment by Bluexin** [comment]
LibrarianLib 1.12.2-4.19.2 (TeamWizardry/LibrarianLib@67734bb95384eb9d2e5e26175964a07aca97ff08)
> both ember rekindled's cinderstaff and root's spells

**Comment by Bluexin** [comment]
https://cdn.discordapp.com/attachments/455388658183307264/608650537487040512/particle_test-1.0.0.zip
World to test with

**Comment by thecodewarrior** [comment]
I have a feeling it’s just them forgetting to call `GlStateManager.enableTexture2D()`, or us incorrectly assuming that the default state should it being disabled.

**Comment by Bluexin** [comment]
Can't assume a default state at any point in mc rendering (especially on modded)

**Comment by thecodewarrior** [comment]
Yeah. My brother was playing modded MC the other day and his diamond chests kept turning green. Looks like someone forgot to set the GL color. Also the AE grindstone’s handle fucks with the lighting of every TESR, making them go disco every time it rotates. However in that case it’s kinda ridiculous that they don’t reset it. You can’t expect everyone to set the lighting parameters in their TESRs.

**Comment by Bluexin** [comment]
XD another funny common one is with some mod (no idea which), certain player rotation fuck up lighting on TESRs as well

**Comment by majijn** [comment]
it's also doing it to astral sorcery's particles but instead of white particles are rendered grey

**Comment by thecodewarrior** [comment]
I'm closing this because 1.12 support is coming to an end and I've been unable to replicate the issue to fix it for the last 1.12 update.
