### ISSUE TITLE
Crashes on startup in Dungeons, Dragons and Spaceshuttles

### ISSUE THREAD

**Issue by LimitNacho** [TeamWizardry/LibrarianLib#116]
When I tried to start up the game, it crashed and said either librarianlib or librarianlib 2 was responsible. It also gave me this report:

https://paste.dimdev.org/ulifipihuz.mccrash

![DDSS Error Screen](https://user-images.githubusercontent.com/54176219/63199096-93604080-c031-11e9-97ae-3abe918718cf.PNG)

**Comment by thecodewarrior** [comment]
As this is verging on a year old and the log won't load anymore, I'm going to close this.
