### ISSUE TITLE
Liblib causes crashes with JEI

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [TeamWizardry/LibrarianLib#120]
https://paste.dimdev.org/betowaxigo.mccrash

**Comment by thecodewarrior** [comment]
The issue seems to be that our code is assuming that `getMapColor` will always be passed a world, but JEI doesn't do that. I'm guessing this occurs when you try to search by color? (I think that's a thing, not sure though)

**Comment by Bluexin** [comment]
Check for annotations in `super`s. Depending on that, the wrong is either on us or on jei :)

**Comment by thecodewarrior** [comment]
Technically it's on JEI, but Minecraft's nullability annotations are so incomplete it makes anything not explicitly annotated suspect. 

```java
// Auto generated package-info by MCP
@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.minecraft.block;

import mcp.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;
```
