### ISSUE TITLE
[1.12.2] [4.19.2] BlockModLog class returns an empty charcoal furnace recipe

### ISSUE THREAD

**Issue by wamc2017** [TeamWizardry/LibrarianLib#121]
Hi,

if Wizardry or Natural Pledge are installed alongside LibrarianLib (both mods are using the BlockModLog class to add their trees), a furnace recipe with empty input is added to the game.
![charcoal](https://user-images.githubusercontent.com/33242447/64652765-ebb61280-d424-11e9-9453-9ae0b5fc662a.png)

It seems "this" in the following line returns Block("Null") or something like this:
https://github.com/TeamWizardry/LibrarianLib/blob/e0f8a5a78b682bc8ef21bca103f7f600254358dd/src/main/java/com/teamwizardry/librarianlib/features/base/block/BlockModLog.kt#L29

I guess those issues are related:
https://github.com/TeamWizardry/Wizardry/issues/298
https://github.com/TeamWizardry/Wizardry/issues/295
https://github.com/Um-Mitternacht/Bewitchment/issues/373

Thanks for looking into this.
Best regards,
wamc

**Comment by thecodewarrior** [comment]
The issue might be that code being called before the ItemBlock is registered. I'm looking into it.

**Comment by murapix** [comment]
This isn't the first time it's been brought up, Wire said it had been fixed but apparently not

**Comment by wamc2017** [comment]
Haven't seen this pull request: https://github.com/TeamWizardry/LibrarianLib/pull/112

I guess those should address this issue...

**Comment by thecodewarrior** [comment]
Oof. Lemme see if I can resolve the couple notes so we can get that merged.
