### ISSUE TITLE
[1.12.2] Possible conflict? Certian mod overlays are grey'd out, depending on the mods.

### ISSUE THREAD

**Issue by SonicX8000** [TeamWizardry/LibrarianLib#122]
Figure I open up an issue here, just in case...

Minecraft: 1.12.2
Forge: 14.23.5.2838

Mods: 4
AutoRegLib-1.3-32
Forgelin-1.8.4
librarianlib-1.12.2-4.19.2-release
Psi-r1.1-76

Mods with Overlays: 5
DynamicSurroundingsHuds-1.12.2-3.5.4.0BETA
OreLib-1.12.2-3.5.2.2
Scannable-MC1.12.2-1.6.3.24
Xaeros_Minimap_1.18.1_Forge_1.12
XaerosWorldMap_1.4.10.1_Forge_1.12

-----

Refer'd Issue:
https://github.com/Vazkii/Psi/issues/525

Some backstory, I've been encountering some rendering issues where they appear to be gray'd out, in a way. After a bit of narrowing down the mods... these are the ones I have left.

I can only seem to get this rendering issue to occur with those mods added together. I tried removing PSI + Auto and couldn't get the render issue to occur. I tried removing Forgelin & librarianlib and couldn't get the issue to occur so I am unsure which one is the cause so... figure I give it a post here.

I dunno whether it be on PSI's / Auto's side or Forgelin / librarianlib but here's some screenshots of the rendering bug...

![](https://cdn.discordapp.com/attachments/377171551155650560/623176700909322251/waypointbug.PNG)
Xaero's Minimap:
Top - The "A" icon is gray'd out yet the other ones are uneffected.
Bottom - Working normally.

![](https://cdn.discordapp.com/attachments/377171551155650560/625026161369677854/dshoverlaybug.PNG)
Dynamatic Surrounding's : HUD
Top - The coloring for the light overlay is gray'd out.
Bottom - The coloring working normally.

![](https://cdn.discordapp.com/attachments/377171551155650560/625028911356706826/scannableoverlaybug.PNG)
Scannable:
Top - You can barely see the overlay, note that DS:H's Light Overlay works as normal when Scannable's Overlay is rendered. Once Scannable's overlay disappears... the Light Overlay will become gray'd out.
Bottom - The Overlay working normally.

-----

There's also this issue here that kinda got me wondering if this is related by any chance...
https://github.com/TeamWizardry/LibrarianLib/issues/115

One more thing to mention is that sometimes this issue doesn't occur and the rendering works normally... or you'll get certain overlays being gray'd out. It happens either by loading the game or by world join. Unsure if it's via world join.

**Comment by Nydid-ForcedDev** [comment]
I'd like to add that this bug (with the same mods), it seems to also affect the lightmap when pressing F5 (Third Person View) and/or F1 (Disable Hud).
With F1 enabled/Hud Hidden: ![2019-09-29_14 23 50](https://user-images.githubusercontent.com/55931128/66474970-a53eec80-ea92-11e9-978c-b403fe727374.png)

Without F1 enabled/Hud Shown: ![2019-09-29_14 24 16](https://user-images.githubusercontent.com/55931128/66475131-036bcf80-ea93-11e9-93a0-c62f9128cdfb.png)

Issue with F5 pressed is that the GUI (eg. Hotbar) goes dark.

**Comment by SonicX8000** [comment]
@Nydid-ForcedDev 
That's pretty crazy in those images... the trees & grass having no color & such.

**Comment by LemADEC** [comment]
If my memory serves right, you need to restore the default texture, especially when drawing during HUD/overlays events, like here: https://github.com/TeamWizardry/LibrarianLib/blob/9b7373a0de71a370d15af4a544c96a92ff2c2fdd/src/main/java/com/teamwizardry/librarianlib/features/particlesystem/GameParticleSystems.kt#L76

**Comment by thecodewarrior** [comment]
I'm not changing the texture in that event. That event just adds text to some lists.

**Comment by thecodewarrior** [comment]
Fixed by 9b7373a

**Comment by aaronhowser1** [comment]
Is there an ETA for an update with this fix?

**Comment by thecodewarrior** [comment]
I can get one out within the next couple days.

**Comment by aaronhowser1** [comment]
Awesome :D

**Comment by thecodewarrior** [comment]
@aaronhowser1 v4.22 is now up
