### ISSUE TITLE
IllegalStateException crash

### ISSUE THREAD

**Issue by bobodoustaud** [TeamWizardry/LibrarianLib#123]
That's a crash. Not a rendering issue, i think.

this crash doesn't occurs everytime, it's a little bit random. It happened to me while using the dimension changer item from aroma's mining dimension mod but not at every try (sometimes it works and sometimes it crashes)

I also use the betterportals mod that enchance third-party transferts. 

crash report : https://pastebin.com/pHB7QcSW

since I'm not sure that it is your problem, i have reported this crash on the betterportals issue tracker too. https://github.com/Johni0702/BetterPortals/issues/403

**Comment by thecodewarrior** [comment]
Looking over the code, literally the only way this can occur is if there's a race condition, which would explain why it's intermittent. When I have more time I'll see if I can reproduce this and create a fix.

**Comment by Johni0702** [comment]
@thecodewarrior 
The `WorldEvent.Load` is fired [on the client](https://github.com/MinecraftForge/MinecraftForge/blob/ff0bb8c83c8de0096aeacf4267eb2a6781285610/patches/minecraft/net/minecraft/client/world/ClientWorld.java.patch#L8) and [on the server](https://github.com/MinecraftForge/MinecraftForge/blob/862289cf56c552c29b51f7c4009a81629a3d7b74/patches/minecraft/net/minecraft/server/MinecraftServer.java.patch#L40) and if the server happens to be an integrated one, then there's your race condition.
`gettingWorld` should probably be a `ThreadLocal` instead.
