### ISSUE TITLE
https://paste.dimdev.org/ufanesohib.mccrash

### ISSUE THREAD

**Issue by sty447** [TeamWizardry/LibrarianLib#126]
Before you report an issue, make sure these boxes are checked.

- [x] Make sure you've got Shadowfacts Forgelin installed.
- [ ] Make sure you're not reporting something that was just fixed.
- [x] Make sure you're not using an old version of LibrarianLib.
- [x] Make sure you're not using Optifine or GLSL Shaders, if it's a rendering issue.
- [x] Make sure you're using Java 7 or greater.

After you've done so, delete this template, and proceed with your issue report.

**Comment by Bluexin** [comment]
> java.lang.OutOfMemoryError: Java heap space
> 422400672 bytes (402 MB) / 3008888832 bytes (2869 MB) up to 3008888832 bytes (2869 MB)

🤔
Are you using a super high res resource pack or something?
We need to make exporting configurable and disabled by default anyway
https://github.com/TeamWizardry/LibrarianLib/blob/36ace518dff925b3607320cbf1cc920437203aa8/src/main/java/com/teamwizardry/librarianlib/core/client/TextureMapExporter.kt#L30-L34
