### ISSUE TITLE
crash with LightningCraft

### ISSUE THREAD

**Issue by BugmanBugman** [TeamWizardry/LibrarianLib#128]
https://paste.dimdev.org/olenupubug.mccrash

**Comment by Bluexin** [comment]
https://github.com/TeamWizardry/LibrarianLib/blob/eb72a3d402054bb134bc47c0b59615e4ad76ef5d/src/main/java/com/teamwizardry/librarianlib/features/base/block/ItemModBlock.kt#L57

We need to check if tabs is supposed to be nullable, but it might be. If so, easy fix, add a question mark in the prototype. If not, it's on them.

**Comment by thecodewarrior** [comment]
The field is never null in the game. The only meaning I could imagine null having in this context would be "everything", but that's already the purpose of `CreativeTabs.SEARCH`, so I'm considering this an error in LightingCraft.
