### ISSUE TITLE
MAJOR rendering issue. @Save or something similar is breaking TESR rendering

### ISSUE THREAD

**Issue by LordSaad44** [TeamWizardry/LibrarianLib#13]
TESRs are not being positioned properly. 
Refraction's mirrors are invisible from one angle and visible on another in single player.
On multiplayer, they render but they render independent of the block and are extremely funky. They move with the player, etc...

**Comment by yrsegal** [comment]
Possibly due to a pushpop in refraction

**Comment by LordSaad44** [comment]
wire leaked a state in the assembly table in refraction. fixed
