### ISSUE TITLE
1.12.2 Subtitles/Captions bug

### ISSUE THREAD

**Issue by DD12-1916** [TeamWizardry/LibrarianLib#134]
Minor Issue:
With LibrarianLib installed, subtitles/captions don’t appear at all, while removing the mod seems to fix this issue.

Tested in a crowded village full of villagers.

**Comment by thecodewarrior** [comment]
I can't seem to replicate this issue

**Comment by DD12-1916** [comment]
In version 4.21? I'll try to do a fresh install with just LibrarianLib and see if that would cause the issue.

**Comment by thecodewarrior** [comment]
Correct

**Comment by DD12-1916** [comment]
Just got back from rigorous testing, which of course meant manually identifying the mod that was causing problems by simple trial-and-error, and well, apparently, this issue is not caused by LibrarianLib, but rather by a mod called 'Random PSIdeas' by 'kamfrede123', which has LibrarianLib as a dependency.
In fact, there was already an open issue regarding this problem in that mod's GitHub page, although it still baffles me how this issue came to be considering that Random PSIdeas only adds items and some mod-related mechanics if I recall correctly.
Anyway, I would like to sincerely apologise for opening this issue without properly confirming if this bug was indeed caused by LibrarianLib or not.
Also, thank you once again for being so accomodating! You are awesome!
