### ISSUE TITLE
Create Foundation base objects

### ISSUE THREAD

**Issue by thecodewarrior** [TeamWizardry/LibrarianLib#146]
One priority with Foundation will be that it shouldn't require a custom superclass, which means we shouldn't need a custom subclass in case you want to extend a vanilla block type.

### Blocks
- [x] Simple (with property defaults)
- [x] *Directional?*
- [ ] *Pillar?*
- [x] *Door?*
- [x] *Trapdoor?*
- [ ] *Falling? (e.g. sand)*
- [ ] *Plant? (e.g. bushes, flowers)*
- [ ] Crop
- [ ] Sapling
  - [ ] Tree growth utilities, possibly including worldgen
- [ ] Leaves
- [x] Log
- [ ] "Building blocks"*
  - [x] Slab
  - [x] Stair
  - [x] Fence
  - [x] Fence gate
  - [x] Wall
  - [ ] *Pane?*
- [x] Pressure plate
- [x] Button

### Items
- [ ] Armor
- [ ] Arrow
- [ ] *Bauble?*
- [ ] *Book?*
- [ ] Bow
- [ ] Food
- [ ] *Food Seed? (e.g. potatoes, which are food but also plantable)*
- [ ] *Fishing Rod?*
- [ ] Seed
- [ ] *Shield?*
- [ ] Sword
- [ ] Tool

### Other
- [ ] *Projectile?*
- [ ] Fluid

**Comment by PhotonChaos** [comment]
The base log block is not properly tagged as a log, hence leaves will still decay, and the block is not flammable.

**Comment by thecodewarrior** [comment]
A number of features, such as flammability, require overriding methods in `Block`. My current plan is to have a set of foundation properties akin to `Block.Properties` which will define this stuff, and then the foundation base blocks will override the necessary methods to use those properties.
