### ISSUE TITLE
When used alongside Simply Jetpacks 2, throws false error

### ISSUE THREAD

**Issue by KuwuroUsagi** [TeamWizardry/LibrarianLib#157]
When testing a modpack I ran into issues with a mod, and upon further investigation, LibrarianLib is causing the issue, [not the other mod](https://github.com/Tomson124/SimplyJetpacks2/issues/13#issuecomment-690484049)
> I'm about 100 mods in, and I can confirm that the following mod causes a crash.
> https://www.curseforge.com/minecraft/mc-mods/librarianlib
> https://github.com/TeamWizardry/LibrarianLib
> 
> This library is required for
> https://www.curseforge.com/minecraft/mc-mods/random-psideas
> https://github.com/Kamefrede/rpsideas
> 
> latest.log without LibrarianLib:
> https://kurousagi.pw/xd/EP8mgbb.txt
> 
> latest.log with LibrarianLib:
> https://kurousagi.pw/xd/YVl6LOH.txt
> 
> crashreport with LibrarianLib:
> https://kurousagi.pw/xd/XS6Xyg6.txt

**Comment by thecodewarrior** [comment]
We don't even touch that method. As someone in the other issue mentioned, it's likely an incompatibility with Cauldron. Does the error occur when launching in a plain Forge environment?

Do note that 1.12 is no longer actively supported. We will still try to fix critical issues, depending on the severity of the issue and the amount of time and effort that would be required to fix it.

**Comment by KuwuroUsagi** [comment]
testing with forge-1.12.2-14.23.5.2854

and the following mods:
SimplyJetpacks2-1.12.2-2.2.16.1
RedstoneFlux-1.12-2.1.1.1-universal(required for above)
librarianlib-1.12.2-4.22
Forgelin-1.8.4(required for the above)

Server starts fine, seems like it's cauldron.
Will check other varying cauldron jars

**Comment by tomheaton** [comment]
Redstone Flux is not a required dependency in the latest version of simply jetpacks 2 for 1.12.2 ( SimplyJetpacks2-1.12.2-2.2.16.1 )

**Comment by KuwuroUsagi** [comment]
Using the same mod combination as mentioned above


<details>
  <summary>testing with kettle-git-HEAD-a8543ec-universal</summary>
crashreport:

https://kurousagi.pw/xd/t4QKToj.txt

latest:
https://kurousagi.pw/xd/H4krOVk.txt
</details>

<details>
  <summary>testing with CatServer-a118ddc-universal</summary>
crashreport:

https://kurousagi.pw/xd/Y0AFNV5.txt

latest:
https://kurousagi.pw/xd/apkekq5.txt
</details>

<details>
  <summary>testing with mohist-1.12.2-21-server</summary>
crashreport:

https://kurousagi.pw/xd/lC39sct.txt

latest:
https://kurousagi.pw/xd/etNyjAT.txt
</details>

<details>
  <summary>testing with Magma-4175a60-server</summary>
crashreport:

https://kurousagi.pw/xd/6x8VOT9.txt

latest:
https://kurousagi.pw/xd/Xi13Ffz.txt
</details>

<details>
  <summary>testing with spongeforge-1.12.2-2838-7.3.0</summary>
spongeforge works, but also does not function as a proper cauldron server jar, but more as a forge mod, and is in general just not ideal when spigot+forge is the goal, but it's good to know it doesn't clash with anything nonetheless
</details>



> Redstone Flux is not a required dependency in the latest version of simply jetpacks 2 for 1.12.2 ( SimplyJetpacks2-1.12.2-2.2.16.1 )

You're correct, just checked, which is weird, because earlier today I got this crash report:
https://kurousagi.pw/xd/9Uj5I04.txt

It probably happened when I was checking other versions of Simply Jetpacks 2
(yup, SimplyJetpacks2-1.12.2-2.2.8.56), wasn't aware they changed their dependencies though in the latest version.

Took out redstone flux and it still ends up in the same crash as seen in the above spoilers though

**Comment by Irgendwer01** [comment]
@thecodewarrior Related to the asm code here
https://cdn.discordapp.com/attachments/615256015704948808/760603715626598440/unknown.png

**Comment by thecodewarrior** [comment]
People use that hook so I couldn't just remove the offending code. I would have to figure out some way to reimplement so it wouldn't wig out when using a custom server.

LibrarianLib is no longer being actively maintained for 1.12 outside of critical issues, and incompatibility with cauldron isn't one. 

Plus that code has been there for [two years](https://github.com/TeamWizardry/LibrarianLib/commit/b9214feed0ec94491ea501471ea342beff03c7f9#diff-cb583887ac55a5f9ffe5682d20de8012R292-R306) without issue, so either something changed on cauldron's end or it took two years before anyone even noticed.

**Comment by Irgendwer01** [comment]
@thecodewarrior before 2 years forge + bukkit 1.12 projects exist, but they was unstable like shit now they work alot better so its no wonder that only now someone seen the issue

**Comment by Irgendwer01** [comment]
@KuwuroUsagi workaround for now: add -noverify argument behind -jar to ur startup script
