### ISSUE TITLE
Crash! V1.10.2 F2221 librarianlib-1.9

### ISSUE THREAD

**Issue by Rickydou** [TeamWizardry/LibrarianLib#17]
https://gist.github.com/Rickydou/1966d2a3edd973c8f43af9cf23922a00

Rolling Back librarianlib-1.8 For moment ..

**Comment by Eladkay** [comment]
God dammit @wiresegal

**Comment by Eladkay** [comment]
@yrsegal

**Comment by Eladkay** [comment]
Wait a minute did you add the forgelin deep?

**Comment by Eladkay** [comment]
dep

**Comment by Morpheus1101** [comment]
I to am getting a crash issue with 1.9 however my crash report differs.... https://puu.sh/tQKI3/0c53d65411.txt

**Comment by Eladkay** [comment]
Another obvious derp by @yrsegal I'll fix it
