### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by skyfallwastaken** [TeamWizardry/LibrarianLib#177]
Improve docs

**Comment by Waterpicker** [comment]
Improve which docs?

**Comment by thecodewarrior** [comment]
I'm well aware that the documentation for LibLib is lacking. Creating documentation is a long, hard, and painful process. I don't have the motivation or mental fortitude to write formal documentation for the entire library.

Feel free to ask for help on [our Discord server](https://discord.gg/KPaZHvq) though.
