### ISSUE TITLE
[1.12.2] the 1.12.2 version maven is broken

### ISSUE THREAD

**Issue by magcicada** [TeamWizardry/LibrarianLib#179]
The mod maven of 1.12.2 doesn't work again.Can not open `http://maven.bluexin.be` website

**Comment by magcicada** [comment]
@Bluexin

**Comment by Bluexin** [comment]
Well yeah it was officially retired years ago in favor of bintray (which also seems down now though).
I'll see if I can boot it back up, but honestly if you need it reliably you'd be better off rehosting it or using some other form of repo :/

**Comment by magcicada** [comment]
but I lost the mod files in maven, so I need redownload them, but the maven is broken now. :)

**Comment by Bluexin** [comment]
It's there now
