### ISSUE TITLE
Shadowfact's Forgelin being missing is not  causing a normal error from missing dependance.

### ISSUE THREAD

**Issue by Divineaspect** [TeamWizardry/LibrarianLib#18]
This causes it to generate a crash report, which will make more headaches  for people and make you look bad when non tech savvy people see the crash.

**Comment by yrsegal** [comment]
Forgelin does not contain an @Mod, so this can't be solved.

**Comment by Eladkay** [comment]
Hm, we might be able to trigger an error if static blocks are ran before the mod language adapter is checked

**Comment by yrsegal** [comment]
You mean a ClassDefNotFound catcher?

**Comment by Eladkay** [comment]
Class.forName checker

**Comment by yrsegal** [comment]
i'm going to go try that

**Comment by yrsegal** [comment]
This didn't work. Waiting on https://github.com/shadowfacts/Forgelin/issues/5

**Comment by yrsegal** [comment]
2bc69cde4deba7c7db5dfa98b2202b734eeadde0
