### ISSUE TITLE
[1.12.2][fall apart]why? my game !?

### ISSUE THREAD

**Issue by chenming0v0** [TeamWizardry/LibrarianLib#180]
this is log       https://mclo.gs/JPIv9oN
I had no problem entering the world the first time
but,the second time I tried to open the world it prompted me that your game crashed

**Comment by chenming0v0** [comment]
My chat gpt told me 
java.lang.NoClassDefFoundError
exceptions

**Comment by SaadArdati** [comment]
It seems all your mods are downloaded from third-party sources. Please only download mods from their official curseforge page.

https://www.curseforge.com/minecraft/mc-mods/librarianlib
https://legacy.curseforge.com/minecraft/mc-mods/shadowfacts-forgelin

**Comment by chenming0v0** [comment]
I'm from China.
I have a penchant for putting notes in front of mods.
So I can see what they mean.

**Comment by chenming0v0** [comment]
I'm sorry my English isn't very good.
But they do come from the official page

**Comment by SaadArdati** [comment]
This mod is discontinued and no longer receives support. If you're sure this is a bug, then you will need to fix it yourself unfortunately.

**Comment by chenming0v0** [comment]
谔谔，好吧，我发现当我第三次重新进入世界时，已经可以进入
![image](https://github.com/TeamWizardry/LibrarianLib/assets/122023652/32860dee-0dda-4271-aab3-dd51952f5738)
