### ISSUE TITLE
Crashes on server-start-up.

### ISSUE THREAD

**Issue by Beanius** [TeamWizardry/LibrarianLib#23]
https://gist.github.com/Beanius/4817c900f02b6ceb16dd943abeb0c06d
B)

**Comment by yrsegal** [comment]
By the *stars*, people, check the recently reported issues...

**Comment by Beanius** [comment]
Ohhhh! Where do i download the fix 👍

**Comment by yrsegal** [comment]
"fixed in dev"

not yet

have patience

**Comment by Beanius** [comment]
Aye that's fair B) Thank you, patience game it is then <3

**Comment by Eladkay** [comment]
https://github.com/TeamWizardry/LibrarianLib/issues/22#issuecomment-279163614
Don't sleep tight tonight

**Comment by Beanius** [comment]
Hehe B)
