### ISSUE TITLE
Caught exception from LibrarianLib Stage 2

### ISSUE THREAD

**Issue by TheOtherMorzie** [TeamWizardry/LibrarianLib#24]
LibrarianLib seems to be causing Minecraft to crash on loading

[Crashlog](http://pastebin.com/rw6W9qhp)

[Modlist](http://pastebin.com/SKRyKFZm)

**Comment by yrsegal** [comment]
Get forgelin.

**Comment by TheOtherMorzie** [comment]
forgelin isn't for 1.10.2?

**Comment by yrsegal** [comment]
https://minecraft.curseforge.com/projects/shadowfacts-forgelin

looks like it is to me

Forgelin barely touches minecraft code, so 1.10 should work in 1.10.2

**Comment by TheOtherMorzie** [comment]
Ahh, thank you, seems to be running well now
