### ISSUE TITLE
Crash after updating Forgelin to latest version 1.3.0 (1.10.2)

### ISSUE THREAD

**Issue by ate0ate** [TeamWizardry/LibrarianLib#25]
Shadowfacts Forgelin updated to 1.3.0, but after updating, LibrarianLib crashes Minecraft during startup. No crash report is generated by this crash so here is the relevant client log. Obviously only the last part is most likely relevant where it states that LibrarianLib cannot start because it needs Forgelin to run. Thanks!

http://pastebin.com/jHg35j0R

**Comment by Eladkay** [comment]
Will be fixed

**Comment by yrsegal** [comment]
Pretty sure this is a forgelin bug

**Comment by ate0ate** [comment]
I shall post it over there as well to be safe.

**Comment by ate0ate** [comment]
Fixed in Forgelin 1.3.1
