### ISSUE TITLE
[1.10.2] Server crashes with NullPointerException on startup.

### ISSUE THREAD

**Issue by DeadSix27** [TeamWizardry/LibrarianLib#27]
Version: librarianlib-1.10.1.jar
Forge: forge-1.10.2-12.18.3.2234-universal.jar

**Description:**

When I start my server on Windows it crashes, however it works just fine on Linux. 

**Stacktrace:** http://pastebin.com/5ct3SJmg

**Comment by Eladkay** [comment]
I blame @yrsegal

**Comment by Eladkay** [comment]
Weird. https://github.com/TeamWizardry/LibrarianLib/blob/master/src/main/java/com/teamwizardry/librarianlib/common/util/autoregister/AutoRegisterHandler.kt#L32
The NPE is in the assignment but not in the calculation. Wire, try making that a `String?`?

**Comment by MysticAura** [comment]
MC: 1.10.2
Forge: 2185, 2254
Library Version: librarianlib-1.10.1
Forgelin: Forgelin-1.3.1, Forgelin-1.4.0

Same issue as above. Windows server refuses to start with librarianlib enabled. Downgrading forgelin made no difference. Only fix was to remove liblib and anything that requires it.

[Crash Log](http://pastebin.com/pxXVpEu4)

**Comment by LordSaad44** [comment]
@MysticAura Did you put BOTH forgelin versions?! ... Only put 1.3.1 in.

**Comment by MysticAura** [comment]
lol, of course I wouldn't put duplicate mods in a pack..sorry I'm surprised at the question. Not to mention then it would've gave a notice that there was a duplicate mod, and not a crash report.

For the record..no I did not try both at once. I was informing that it happened with each of them.

**Comment by Morpheus1101** [comment]
Im getting a somewhat similar but slightly different error to this i feel may be attributed with this...

https://puu.sh/uYKuK/ba25642503.txt

**Comment by thecodewarrior** [comment]
Yeah, for some reason those annotations aren't bundled in newer versions of Forgelin. Downgrade it for now, we're phasing those annotations out for future liblib versions.

**Comment by Zygus42** [comment]
Same crash here - only on server not in singleplayer.  Tried with Forgelin 1.3.1 and 1.4.1.  Went back to librarianlib 1.8 without forgelin and works fine, but also had to go back to an earlier version of Natural Pledge.

Crash Report:
[crash-2017-04-20_22.58.41-server.txt](https://github.com/TeamWizardry/LibrarianLib/files/943906/crash-2017-04-20_22.58.41-server.txt)

**Comment by thecodewarrior** [comment]
I'm going to close this because the AutoRegisterHandler has been phased out in favor of a new AnnotationMarkerProcessor system in LibLib 3.0
