### ISSUE TITLE
Crash on startup: NoClassDefFoundError: org/jetbrains/annotations/NotNull

### ISSUE THREAD

**Issue by MCEventHorizon** [TeamWizardry/LibrarianLib#28]
http://pastebin.com/RgLjHhEh

**Comment by LordSaad44** [comment]
downgrade forgelin to 1.3.1

**Comment by Morpheus1101** [comment]
Im also getting this Error and will downgrade ForgeLin

**Comment by Morpheus1101** [comment]
Could we possibly change the name of this report to better suit and others to find it since this issue is still on going.

**Comment by thecodewarrior** [comment]
## Solution

#### Downgrade ForgeLin to version 1.3.1

## Reason

#### After version 1.3.1 ForgeLin does not package jet brains annotations

**Comment by Eladkay** [comment]
Is this a permanent fix? I think that a simple decompile will fix it.
