### ISSUE TITLE
1.11.2 Server Re-join Crash

### ISSUE THREAD

**Issue by EmosewaPixel** [TeamWizardry/LibrarianLib#32]
I'm using version 2.0 (as the latest doesn't work with Natural Pledge) and the second time someone joins the server (after they've exited the game, not just the server) they get a fatal error. Here's the log: https://drive.google.com/file/d/0B7aL8W87LjOtRnI1LUtCS3JrZ00/view

**Comment by Eladkay** [comment]
@yrsegal for the not working with np part

Can you PLEASE post only the crash and not the entire log?

**Comment by EmosewaGamer** [comment]
Well the thing is that the client doesn't crash and just gets disconnected so there is no crash log. Here's only the cause of the crash: https://pastebin.com/TqdGX1jG

**Comment by Eladkay** [comment]
yes that's many times more helpful because now i can blame @thecodewarrior

**Comment by EmosewaGamer** [comment]
Lel. Could you please stop blaming people and tell them to fix it? I kinda want to release a server for my pack in 2 days. If not then there's always the update after. XD

**Comment by thecodewarrior** [comment]
I think the solution here is to have @yrsegal update NP to use LibLib 3.0. Partially because he should anyway, and partially because it's almost impossible to debug serialization errors in LibLib 2.0. 

Also, I won't have time to fix this in the next few days as I'm competing in ModOff and I have over a day's worth of lost time to make up.

**Comment by EmosewaGamer** [comment]
Good luck then!

**Comment by Eladkay** [comment]
> Lel. Could you please stop blaming people and tell them to fix it? I kinda want to release a server for my pack in 2 days. If not then there's always the update after. XD
 @EmosewaGamer well, it's code's system and wire wrote NP so it's natural. Speaking of code's Modoff, wire is a judge in it and I'm a organizer so I think we all won't have time for the coming few days. Besides I'm not even a liblib dev so I didn't owe you any response at all but instead I decided to route it to whoever can fix it to make sure it's noticed.

**Comment by EmosewaGamer** [comment]
I know that you're not.

**Comment by EmosewaGamer** [comment]
Welp you might have fixed it, but I think that this should stay here for the NP problem.

**Comment by yrsegal** [comment]
waiting on models from wiiv

**Comment by EmosewaGamer** [comment]
Do you think it could be done in a day's time from now? I really don't like removing and after readding mods in my pack.

**Comment by Eladkay** [comment]
Well, considering that Saad and Code are competing in modoff, wire is a judge, escapee and I are organizers.... probably not.

**Comment by EmosewaGamer** [comment]
Well then, I'm gonna have to do that.
