### ISSUE TITLE
crash with 3.1.4 version

### ISSUE THREAD

**Issue by 0Navis0** [TeamWizardry/LibrarianLib#34]
I get this crash with new version of librarianlib. https://pastebin.com/FSWKne9e

**Comment by kreezxil** [comment]
Also getting a crash here but this time with the server, didn't test out the client, probably will get what @Hypsellis  got.

3.1.4 crashes dedicated server Forge 1.11.2 build 2304

Notes:
     on startup - invalid side SERVER

crash report:
https://gist.github.com/f4bef35bee0250624dd0cd9ac508eaa8

fml server latest:
https://gist.github.com/478e620db7e8313fd613f28437294353

**Comment by Eladkay** [comment]
That's what happens when wire rewrites my code

**Comment by kreezxil** [comment]
Wire? I rolled back a version and all is fine now.

**Comment by yrsegal** [comment]
> when wire rewrites my code

elad, this is my code 100%

**Comment by Bluexin** [comment]
Should be fixed in one of my recent pushes.
If not, make new issue.
