### ISSUE TITLE
Crash On Load

### ISSUE THREAD

**Issue by ChloeDawn** [TeamWizardry/LibrarianLib#35]
Crashes to desktop during loading/startup.
This crash does not occur when I remove LibrarianLib.

**LibLib version:** [3.1.4.2](https://minecraft.curseforge.com/projects/librarianlib/files/2426432)
**Forge version:** [1.11.2-13.20.0.2304](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11.2-13.20.0.2304/forge-1.11.2-13.20.0.2304-changelog.txt)

**Crash report:** [paste.ee/lL8qB](https://paste.ee/p/lL8qB)

**Comment by ChloeDawn** [comment]
https://github.com/Vazkii/Quark/issues/449

**Comment by SaadArdati** [comment]
This is what asm does to a man.

**Comment by Bluexin** [comment]
fixed alongside Vazkii/Quark#449
