### ISSUE TITLE
Request by FoolCraft DevTeam - 

### ISSUE THREAD

**Issue by Jo-Mamma75** [TeamWizardry/LibrarianLib#36]
- [X] Make sure you've got Shadowfacts Forgelin installed.
- [X] Make sure you're not reporting something that was just fixed.
- [X] Make sure you're not using an old version of LibrarianLib.
- [X] Make sure you're not using Optifine or GLSL Shaders, if it's a rendering issue.
- [X] Make sure you're using Java 7 or greater.

I am posting this on behalf of the entire FoolCraft Pack Development Team in hopes that you will be able to address this issue.  It could (and likely should) be considered a duplicate of #33 but that particular issue has not been updated in quite a while.  We do have an open issue in our Github specifically for this problem if you would care to have a look please do so.  https://github.com/scalda/FoolCraft/issues/550

We have had several reports of the same type of crash as discussed in the above mentioned issue but, at the same time, we have not been able to reproduce it on any of our servers.  However, it does appear to be an issue nonetheless.  We are hoping that you could look into this a little further and perhaps offer a solution to the problem and/or an update.

If, however, you are not planning on continuing development of this mod and Natural Pledge for 1.10.2, then please let us know so that we can take that information under advisement for the purposes of determining the fate of the mod in our pack.  We would love to leave it in the pack but we also want to make the pack as stable and consistent for the general public as possible.

Thank you for your time and consideration and we look forward to hearing back from you.

Jo_Mamma75
Iskall85 Community Administrator
FoolCraft DevTeam

**Comment by Jo-Mamma75** [comment]
Just a heads up. The guys in our Github have done some additional testing and think they may have a solution involving downgrading the two library jars required for Natural Pledge.  You might have another look at the issue I referenced above and read through the last couple of days.

**Comment by yrsegal** [comment]
@machinespray is the maintainer for NP now, so long as he wants to be.
