### ISSUE TITLE
Pre-initialization crash

### ISSUE THREAD

**Issue by BestMordaEver** [TeamWizardry/LibrarianLib#38]
I run little private server. Currently it is official Forge build for 1.10.2. 
My current modpack required LibLib, so I added it and tried to run. Client worked properly and stable, but when I tried to run server with this modpack it crashed. 
Server log says: 
Fatal errors were detected during the transition from PREINITIALIZATION to INITIALIZATION
...
Caught exception from LibrarianLib Stage 2 (librarianliblate)
java.lang.ExceptionInInitializerError
	at com.teamwizardry.librarianlib.common.util.autoregister.AutoRegisterHandler.handle(AutoRegisterHandler.kt:32)...

The same problem appears even if I launch server only with LibLib and Forgelin. The problem does not appear when LibLib, Forgelin and dependent mods are removed. A lot of mods use LibLib, so it would be great to hear from you how to fix this bug. Also, should I attach log or crash report?

**Comment by yrsegal** [comment]
That is not nearly enough information. Give a larger log, please.

**Comment by BestMordaEver** [comment]
[crash-2017-07-31_19.14.42-server.txt](https://github.com/TeamWizardry/LibrarianLib/files/1188186/crash-2017-07-31_19.14.42-server.txt)
[fml-server-latest.txt](https://github.com/TeamWizardry/LibrarianLib/files/1188190/fml-server-latest.txt)

**Comment by yrsegal** [comment]
That's a super old version of liblib. weird.

**Comment by BestMordaEver** [comment]
That's the one I found on CurseForge, right here
https://minecraft.curseforge.com/projects/librarianlib?gameCategorySlug=mc-mods&projectID=252910
