### ISSUE TITLE
Lib file crashes SMP on Load

### ISSUE THREAD

**Issue by Towsty** [TeamWizardry/LibrarianLib#4]
Crash Report:
https://gist.github.com/Towsty/74c34abc6d721f6734d2663b5555b824

Log: (issue around line 26072)
https://gist.github.com/Towsty/be32694a21182e6e785deb7cca03e35f

**Comment by yrsegal** [comment]
there's no error visible in either gist.

**Comment by Towsty** [comment]
They're truncated by gist, you can view the raw file but its a little annoying to do it that way. I've uploaded the log and crash report.

[fml-latest.txt](https://github.com/TeamWizardry/LibrarianLib/files/587961/fml-latest.txt)
[crash.txt](https://github.com/TeamWizardry/LibrarianLib/files/587962/crash.txt)

**Comment by yrsegal** [comment]
please give us just a snippet of the crash next time. We don't need the whole log.

**Comment by yrsegal** [comment]
9a4e47cc2d54c6dcc1e184c1e03efe4ede66e14c
