### ISSUE TITLE
LIBRARIANLIB-1.10.1 crashing my Server one on PC but not another?

### ISSUE THREAD

**Issue by nvrsbr** [TeamWizardry/LibrarianLib#41]
Yes the correct version of Shadowfacts Forgelin is installed.
Using LIBRARIANLIB-1.10.1
Java 8 64bit

Run the Resonant Rise server on my Client PC and it runs fine.
Run the same server on my Server PC and LIBRARIANLIB-1.10.1 crashes the server?

Same OS and Same Java version on both PCs.

Any ideas what may be causing the crash on the server PC?

**Comment by yrsegal** [comment]
I'd love an actual crash log...

**Comment by SaadArdati** [comment]
Well paste your log, then we'll talk....

**Comment by nvrsbr** [comment]
Here is the crash report:
https://pastebin.com/Z9CemUuD

**Comment by yrsegal** [comment]
What OS is the server pc?

**Comment by nvrsbr** [comment]
Windows 10 64bit

**Comment by Eladkay** [comment]
I think we fixed that, didn't we

**Comment by Bluexin** [comment]
@nvrsbr please test with latest liblib version now, if still needed.
We'll close in 3 days time if we haven't got any reply back from you. (if we remember to)

**Comment by Eladkay** [comment]
mildly late, but yes
