### ISSUE TITLE
[MC 1.12.2] LibrarianLib 4.0 works, but is not marked as such on Curse

### ISSUE THREAD

**Issue by sandalle** [TeamWizardry/LibrarianLib#43]
[LibrarianLib 4.0](https://minecraft.curseforge.com/projects/librarianlib/files/2452915) works on MC 1.12.2 (Forge Mod Loader 14.23.0.2515), but is not marked as such on Curse disallowing modpacks from using it.

**Comment by Eladkay** [comment]
ddddd

**Comment by Eladkay** [comment]
translation: i did it

**Comment by sandalle** [comment]
Thank you for the quick turnaround @Eladkay . :)
