### ISSUE TITLE
Crash durring preinit

### ISSUE THREAD

**Issue by Divineaspect** [TeamWizardry/LibrarianLib#44]
Only one of the people playing is having this issue.

https://pastebin.com/LcXVFMLf

**Comment by yrsegal** [comment]
@thecodewarrior

**Comment by thecodewarrior** [comment]
What the hell? Ummm... maybe try redownloading liblib? I’m honestly not sure how in the world this could happen.

**Comment by Divineaspect** [comment]
tried reedownloading (using the ATL launcher), no change.

**Comment by Divineaspect** [comment]
resolved, was a single bit off in java...

**Comment by yrsegal** [comment]
👌
