### ISSUE TITLE
Client Crash - CME - com.teamwizardry.librarianlib.features.particle.ParticleRenderLayer.render

### ISSUE THREAD

**Issue by ProsperCraft** [TeamWizardry/LibrarianLib#49]
https://gist.github.com/ProsperCraft/12eeb1b4c67ea2d0ef90c531832bcad9

I was testing my pack, making single player worlds while waiting for the curse approval, and I had just placed down a prefab, opened the chest with items provided, and went to shift click the leather armor into their slots and the client crashed.

Pack - https://minecraft.curseforge.com/projects/towncraft/  - A town building modpack for 1.12.2
Version .29

**Comment by ProsperCraft** [comment]
It happened again - 

https://gist.github.com/ProsperCraft/b3500572f40af5db1d8958ee0ac43a04

Player loaded into a single player world.

Pack version .39

**Comment by yrsegal** [comment]
@thecodewarrior ?

**Comment by ProsperCraft** [comment]
Happened again, single player world - https://gist.github.com/ProsperCraft/74f7704f768f51b1702b2887db861fab

Pack version 1.23

**Comment by thecodewarrior** [comment]
What version of LibLib are you using? ParticleRenderManager.kt only has 299 lines, so I don't see how an error could occur on line 303.

**Comment by ProsperCraft** [comment]
librarianlib-1.12.2-4.7

**Comment by Bluexin** [comment]
Assuming fixed in recent version
