### ISSUE TITLE
[1.10.2]Version 1.5 crashes on loading screen/Refraction 1.1 crash

### ISSUE THREAD

**Issue by JAWSAWN** [TeamWizardry/LibrarianLib#5]
Using it for the Refraction
https://gist.github.com/JAWSAWN/a56044784e1b44991fbb159a431240d9

**Comment by JAWSAWN** [comment]
Now I updated the refraction and downgraded LLib to 1.4 and it still crashed

**Comment by Eladkay** [comment]
LLib is something else. Are you sure you have LibrarianLib installed?

**Comment by JAWSAWN** [comment]
I abvrivated it. I meant LibLib

**Comment by yrsegal** [comment]
This is a known bug with TheOneProbe. This will be fixed next version.

**Comment by yrsegal** [comment]
Fixed for next version.

**Comment by Eladkay** [comment]
that's not how you fix a bug
