### ISSUE TITLE
Server side crash

### ISSUE THREAD

**Issue by xAlicatt** [TeamWizardry/LibrarianLib#50]
https://gist.github.com/xAlicatt/6222cdb0682ac3f96580fc66cf17b1dc

Client side loads up fine, just seeing this on server side. Liblib 4.9. I tried rolling it back to the 4.8, but I'm getting the same (or a similar looking) error.

**Comment by SaadArdati** [comment]
Will be fixed in the next update. We are aware of this problem.

**Comment by xAlicatt** [comment]
I figured as much. Thank you for your hard work. :)
