### ISSUE TITLE
Game Initialization Crash

### ISSUE THREAD

**Issue by kwstoudt** [TeamWizardry/LibrarianLib#51]
My game keeps crashing while initializing. In order to stop the crashes, I have to disable this mod, which also causes me to disable another mod I have because of dependency.

Here is the error I get every time:
```
The game crashed whilst initializing game
Error: java.lang.NoSuchMethodError: com.teamwizardry.librarianlib.features.kotlin.CommonUtilMethods.toNBT$default(Ljava/lang/Object;ZILjava/lang/Object;)Lnet/minecraft/nbt/NBTBase;
```
I have had this issue with both the current and last prior version of this mod.

Due to the number of mods I have installed, I have listed them in a pastebin paste: https://pastebin.com/E6zT2BcH

**Comment by yrsegal** [comment]
Could you give us more of your log?

**Comment by Eladkay** [comment]
mmh, [log](https://imgur.com/a/MsjkO)

**Comment by yrsegal** [comment]
Those are incredibly delicious but also don't contain any code

**Comment by kwstoudt** [comment]
https://pastebin.com/Dng1RHSp

**Comment by yrsegal** [comment]
This is an issue with [`thecodewarrior/Catwalks3`](https://github.com/thecodewarrior/Catwalks3) not with LibrarianLib.
