### ISSUE TITLE
Client crash - Could not initialize class com.teamwizardry.librarianlib.features.saving.FieldType

### ISSUE THREAD

**Issue by NewEvolution** [TeamWizardry/LibrarianLib#52]
Mods installed via _[All The Mods 3 v5.9.2](https://www.curseforge.com/minecraft/modpacks/all-the-mods-3/files)_ via the Curse/Twitch client.

Consistent crash on launch with
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from LibrarianLib Stage 2 (librarianliblate)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.teamwizardry.librarianlib.features.saving.FieldType
```
Full log on [pastebin](https://pastebin.com/7qWr5qta)

**Comment by SaadArdati** [comment]
update Liblib

**Comment by NewEvolution** [comment]
LibrarianLib updated to 4.9 via [Curseforge](https://minecraft.curseforge.com/projects/librarianlib/files) & manual jar replacement results in identical crash.

For completeness, wiped install, reinstalled & updated LibrarianLib via Curse profile editor, same result.

[Crash log](https://pastebin.com/yQLAhmnA)

**Comment by NewEvolution** [comment]
Turns out it was an outdated Java/OS X being bad at Java issue.

The Java control panel reported the current java as up-to-date at 1.8.161 but was managing a Java located at `/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java` while the system was using `/System/Library/Frameworks/JavaVM.framework/Versions/Current/Commands/java` which was still at version 1.8.05

Reinstalled from Oracle and everything's sorted.
