### ISSUE TITLE
Crash upon singleplayer world join with hooked 1.0.1

### ISSUE THREAD

**Issue by Darkmega18** [TeamWizardry/LibrarianLib#53]
Before you report an issue, make sure these boxes are checked.

- **[tick ]** Make sure you've got Shadowfacts Forgelin installed.
- **[not sure. how can I know? :V ]** Make sure you're not reporting something that was just fixed.
- **[4.12, from 2 days ago ]** Make sure you're not using an old version of LibrarianLib.
- **[it's something about NBT, and it worked last version ]** Make sure you're not using Optifine or GLSL Shaders, if it's a rendering issue.
- **[tick ]** Make sure you're using Java 7 or greater.

Something about deserializing hookcaps.

https://pastebin.com/StNXGEnR

I reported it to hooks' comment section, but figured librarianlib has a issues so posted it here too.

**Comment by thecodewarrior** [comment]
This is an issue with LibrarianLib, but I can work around it in Hooked pretty easily. A hotfix is imminent.

**Comment by thecodewarrior** [comment]
The 1.0.2 hotfix of Hooked is currently under review.

**Comment by Darkmega18** [comment]
Roger, I'll download it next time I close and reload. :)
