### ISSUE TITLE
Kotlin reflection failure

### ISSUE THREAD

**Issue by ejektaflex** [TeamWizardry/LibrarianLib#64]
SavingFieldCache.getClassFields seems to be throwing a KotlinReflectionInternalError. The issue is discussed more in depth with crash reports here:

ejektaflex/NaturalPledge#4

**Comment by Rikshy** [comment]
Did you try the solution i sugguested yesterday on liblib discord?

**Comment by ejektaflex** [comment]
Yes, the problem still occurs. Interestingly, this only happens in the production jar, and not in the dev workspace.

**Comment by Bluexin** [comment]
Oddly enough, my TEs are working even in release, using latest liblib.
I see you're using a fairly old one in dev, and 4.15 in that release test.
Mind to test with 4.16? @ejektaflex

**Comment by ejektaflex** [comment]
@Bluexin Yeah, I updated mappings to stable_39 and LibLib to 4.16 [here](https://github.com/ejektaflex/NaturalPledge/commit/729c12e843c605fa68253f4c41e94b3a444fd5d5). Still no luck in release.
