### ISSUE TITLE
SpriteRenderModule renders the sprite upside-down

### ISSUE THREAD

**Issue by GlassSpirit** [TeamWizardry/LibrarianLib#73]
Particle system SpriteRenderModule renders the sprite upside-down
For example the default carrot sprite from minecraft
https://imgur.com/iaN5L84

**Comment by SaadArdati** [comment]
wtf. I've never ever ever had this happen. Show your code line please.

**Comment by GlassSpirit** [comment]
My code is slightly changed code from example [link](https://github.com/TeamWizardry/LibrarianLib/blob/1.12/src/example/java/com/teamwizardry/librarianlib/test/particlesystem/examples/AccelerateAway.kt)

**Comment by GlassSpirit** [comment]
Also that code doesn't even compile because of missing StoredBinding.load function...

**Comment by GlassSpirit** [comment]
Btw what is the latest version I can use for development?

**Comment by Bluexin** [comment]
```
Also that code doesn't even compile because of missing StoredBinding.load function..
```
Most likely you're not using the latest dep version then.
I know there was some effort to stabilize at some point, not sure where that's at though.

**Comment by thecodewarrior** [comment]
That’s because in a GUI (what the sprite code was originally designed for) +Y is down, but in-world +Y is up

**Comment by GlassSpirit** [comment]
But that is not the sprite code, it is code for particle system, isn't it?
`com.teamwizardry.librarianlib.features.particlesystem.modules.SpriteRenderModule`

**Comment by thecodewarrior** [comment]
I totally looked at your code (EDIT: and I also definitely paid attention to the title) before commenting. Totally.

Lemme launch MC and see if my Y sign is wrong

**Comment by thecodewarrior** [comment]
I don't know how I missed it when our own test displays them upside down…

rip. Patch incoming.

**Comment by thecodewarrior** [comment]
I also made a change so if any of the custom facing vector's components are NaN it will revert to billboarding to the player, so by passing NaN you can have both explicit facing and player-facing particles.
