### ISSUE TITLE
InterpColorComponents missing color value check

### ISSUE THREAD

**Issue by GlassSpirit** [TeamWizardry/LibrarianLib#75]
[InterpColorComponents](https://github.com/TeamWizardry/LibrarianLib/blob/1.12/src/main/java/com/teamwizardry/librarianlib/features/particle/functions/InterpColorComponents.kt) is missing color value check.
For example if I want to set color function based on InterpColorComponents(Color.BLACK, Color.WHITE), it throws exception `java.lang.IllegalArgumentException: Color parameter outside of expected range: Red Green Blue` and crashes

**Comment by GlassSpirit** [comment]
Guess it is because constructor of java.awt.Color that takes float values multiplies them by 255, so in InterpColorComponents you should cast parameters to integer before passing them to Color constructor

**Comment by thecodewarrior** [comment]
Derp on my part. Yeah that would be why.
