### ISSUE TITLE
Unable to depend on latest build

### ISSUE THREAD

**Issue by GlassSpirit** [TeamWizardry/LibrarianLib#76]
I am trying to depend on latest active build (librarianlib-liblibx-1.12.2:4.16-SNAPSHOT), but maven pom seems broken a bit.
Log : https://gist.github.com/GlassSpirit/9fb2ac510763d0bef2775eb78c6280f0

Also a question, what version should I use for development?
What I can and cannot shadow inside my mod jar (forgelin, liblib, their dependencies)?
Now I am shadowing only sponge mixins system.

**Comment by Bluexin** [comment]
liblibx branch has more experimental and unfinished features, so I don't recommend depending on that one.
That error seems very weird, and I've never seen it (the `groupId` is set properly in the pom, see for yourself).
I use `com.teamwizardry.librarianlib:librarianlib-1.12.2:4.17-SNAPSHOT` in dev (no classifier is non obfuscated -> on stable_39, and with no shaded/included libs).
Don't ever shade anything in minecraft modding, though you can use [Forge's contained dependencies](https://mcforge.readthedocs.io/en/latest/gettingstarted/dependencymanagement/) instead. In which case, it's safe to shade anything, though I don't recommend including big libraries (like liblib & forgelin) as it'd dramatically increase your jar size (and are required by other mods anyway). Both of these contain (or shade in the case of Forgelin) their dependencies.
