### ISSUE TITLE
Unable to run liblib on SpongeForge server

### ISSUE THREAD

**Issue by GlassSpirit** [TeamWizardry/LibrarianLib#77]
Server is crashing when trying to load LibrarianLib.
Latest log : [link](https://gist.github.com/GlassSpirit/641220f328d1fa516f32946845fe9014)
Debug log : [link](https://gist.github.com/GlassSpirit/6833134b4075af635189d4db6a1b8a27)
Seems like liblib asm hooks have conflicts with sponge server

**Comment by Bluexin** [comment]
That's new, I've used liblib on spongeforge servers for years o.O

**Comment by GlassSpirit** [comment]
Do you have any ideas what could be wrong?
I only have spongeforge, forgelin and liblib installed to make it crash.

**Comment by GlassSpirit** [comment]
Error occurs since liblib 4.16-SNAPSHOT, on 4.15 everything works fine

**Comment by phit** [comment]
this made it into 4.17 now and we are seeing a bunch of reports for this on the Sponge Discord server

**Comment by MysteriousEmpire** [comment]
yea the devs lied to me then yesterday on discord cause they told me it was not on their end

**Comment by gabizou** [comment]
Someone run the server with `-Dlegacy.debugClassLoading=true` with and without SpongeForge. If the class `net.minecraft.util.text.TextComponentBase` shows up, need the *full log until that point*.

**Comment by darkcamo12** [comment]
are there any updates to this issue? 
the newest beta release of FTB Interactions has the latest version of librarianlib (4.18)

**Comment by darkcamo12** [comment]
> Someone run the server with `-Dlegacy.debugClassLoading=true` with and without SpongeForge. If the class `net.minecraft.util.text.TextComponentBase` shows up, need the _full log until that point_.

sorry missed this before posting 

here are the 2 requested logs

With Sponge: [Link](https://gist.github.com/darkcamo12/5fe501b1318a267b67026c5580d67962)
Without Sponge: [Link](https://gist.github.com/darkcamo12/e84f794d9070508d63490937dc91d5ad)

**Comment by Bluexin** [comment]
If someone else could confirm [this jar](https://oss.jfrog.org/artifactory/libs-snapshot/com/teamwizardry/librarianlib/librarianlib-1.12.2/bugfix-sponge-compat-4.20-SNAPSHOT/librarianlib-1.12.2-bugfix-sponge-compat-4.20-20190524.142005-1-release.jar) fixes this issue, we'll publish it ASAP.

**Comment by BedrockLegends** [comment]
Can confirm this new fixes has fixed the issue with Sponge and works on there latest update from two days ago

**Comment by elementalistic** [comment]
Confirm server running and joinable with the attached jar.
Using spongeforge-1.12.2-2768-7.1.5.jar

I did have an issue on the client side with it throwing a crash of "java.lang.VerifyError: Expecting a stackmap frame at branch target 81".  Launching with "-noverify" got pass it.  This was replacement librarianlib-1.12.2-4.17.jar.old.
Modpack: Omnifactory 1.0

**Comment by Bluexin** [comment]
@elementalistic plese open a separate issue about it, and attach relevant logs/reports, thanks :)

**Comment by Bluexin** [comment]
https://minecraft.curseforge.com/projects/librarianlib/files/2725449
