### ISSUE TITLE
"Argument is not an array" error in singleplayer

### ISSUE THREAD

**Issue by Sunconure11** [TeamWizardry/LibrarianLib#80]
https://paste.dimdev.org/azixoqidoj.mccrash

This is happening with the latest build of LibrarianLib on a server, mind you.

**Comment by sandalle** [comment]
Same, but on a client only (haven't updated my server yet), when trying to use the mouse scroll wheel after updating to librarianlib-1.12.2-4.17 to fix https://github.com/TeamWizardry/Wizardry/issues/255 .

Crash report: [crash-2019-04-30_15.37.45-client.txt](https://github.com/TeamWizardry/LibrarianLib/files/3133362/crash-2019-04-30_15.37.45-client.txt)

**Comment by DestinyPlayer** [comment]
https://paste.dimdev.org/dagarunesi.mccrash
Same here, but only when the 0.10.0 version of Wizardry is installed

**Comment by Sunconure11** [comment]
https://cdn.discordapp.com/attachments/242885249351155713/574037543830552596/librarianlib-1.12.2-4.17-fat.jar

Try this build, I was told to test it out, but ATM, cannot do so.

**Comment by kantsche** [comment]
Me too~ in singleplayer https://paste.dimdev.org/xuhexiqepi.mccrash
tried last, current and the -fat version all the same..

**Comment by sandalle** [comment]
This issue no longer occurs with librarianlib-1.12.2-4.18 posted to Curse Forge, thank you. :)
