### ISSUE TITLE
Add context to animation errors

### ISSUE THREAD

**Issue by Bluexin** [TeamWizardry/LibrarianLib#85]
This would make debugging them a lot easier ;-;
Some of the info that could be useful in the exception messages : 
 * toString of the instance owning the field being animated
 * description of the field being animated
 * toString of the current field value

**Comment by thecodewarrior** [comment]
Something like this would still be helpful in LibLib 5, though implementing it would be limited due to the changes in how the animation system works now.

**Comment by thecodewarrior** [comment]
This isn't entirely relevant any more since animations are handled by the GuiValue and not an external object.
