### ISSUE TITLE
sprite sheet sprites not animating properly

### ISSUE THREAD

**Issue by LordSaad44** [TeamWizardry/LibrarianLib#9]
```{
	"spritesheet":{
		"textureWidth":166,
		"textureHeight":4158,
		"sprites":{
			"bg":{
				"pos":[10, 0, 155, 219],
				"frames":[18]
			}
		}
	}
}
```
http://i.imgur.com/jxx9WRS.png

http://i.imgur.com/imMxysh.gifv

**Comment by thecodewarrior** [comment]
For one thing it should be `frames: 18`

I'll have to look into that though.

**Comment by thecodewarrior** [comment]
Can I get the sprite sheet used to reproduce this issue? The provided image appears to be a screenshot.
