### ISSUE TITLE
Spell doesn't load into spellforger's codex, and codex gives a "that book didn't load correctly" message

### ISSUE THREAD

**Issue by QuotableRaven** [TeamWizardry/LibrarianLib#94]
When opening the spellforger's codex an error message appears behind it saying "that book didn't load correctly..." this persists with server, and client restarts and creating new books as well. Additionally when making spells, no matter what is chosen or how many are made only one entry ever appears in the codex, with the only ingredient being a nacre pearl.
Here's an image of the nacre pearl spell structure:
![2018-08-21_15 40 06](https://user-images.githubusercontent.com/23146403/44427960-9b89bb00-a558-11e8-9461-b4e5af332103.png)

And a couple of pictures showing the book error:
![2018-08-21_15 40 08](https://user-images.githubusercontent.com/23146403/44428010-b825f300-a558-11e8-86c1-659204327186.png)
![2018-08-21_15 40 15](https://user-images.githubusercontent.com/23146403/44428021-bfe59780-a558-11e8-9040-a5e083c59e0c.png)

[2018-08-20-4.log.gz](https://github.com/TeamWizardry/Wizardry/files/2307933/2018-08-20-4.log.gz)
[latest.log](https://github.com/TeamWizardry/Wizardry/files/2307935/latest.log)

I hope this is informative for you. If there's anything else you need please let me know.

**Comment by SaadArdati** [comment]
Update: Spells load but the message appears on servers wtihout reason

**Comment by thecodewarrior** [comment]
After the next update we're dropping support for 1.12 outside of major issues.
