### ISSUE TITLE
Sponge compat jar throwing verifyError on client

### ISSUE THREAD

**Issue by elementalistic** [TeamWizardry/LibrarianLib#99]
Modpack: Omnifactory 1.0

Replacing the librarianlib-1.12.2-4.17.jar with librarianlib-1.12.2-bugfix-sponge-compat-4.20-20190524.142005-1-release.jar on the client and then launching the game results in the attached crash logs(I've included 2 separate ones).

https://gist.github.com/elementalistic/8f968835251bbcdc11ad6aefd4108a9e

Using "-noverify" in the jvm parameters bypasses the check and launches fine, allowing connection to a server with the same librarianlib version.

See Unable to run liblib on SpongeForge server #77 for original link to the jar.

**Comment by Bluexin** [comment]
[This snapshot build](https://oss.jfrog.org/artifactory/libs-snapshot/com/teamwizardry/librarianlib/librarianlib-1.12.2/bugfix-99-asm-frames-4.20-SNAPSHOT/librarianlib-1.12.2-bugfix-99-asm-frames-4.20-20190524.195124-1-release.jar) should fix it.
If you can confirm, I'll be able to merge into main branch :)

**Comment by elementalistic** [comment]
No go sorry :(

Crashes during loading.

https://gist.github.com/elementalistic/1735d05fed5486b6a6977760c361dec2

**Comment by Bluexin** [comment]
Sorry for the delay.
Could you please try with this build? https://oss.jfrog.org/artifactory/libs-snapshot/com/teamwizardry/librarianlib/librarianlib-1.12.2/bugfix-99-asm-frames-4.20-SNAPSHOT/librarianlib-1.12.2-bugfix-99-asm-frames-4.20-20190607.190951-3-release.jar

**Comment by Bluexin** [comment]
https://minecraft.curseforge.com/projects/librarianlib/files/2725449
